name: 构建Flutter Engine Android ARM64

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches: [ main ]  # 当推送到main分支时触发
  pull_request:
    branches: [ main ]  # 当PR针对main分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa-dev gcc g++ pkg-config
          sudo apt-get install -y lib32stdc++6 libstdc++6 libncurses5
          sudo apt-get install -y ninja-build cmake clang
      
      - name: 安装JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: 安装depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=$PWD/depot_tools:$PATH" >> $GITHUB_ENV
      
      - name: 获取Flutter Engine仓库
        run: |
          mkdir -p flutter-engine && cd flutter-engine
          cat > .gclient <<EOF
          solutions = [
            {
              "managed": False,
              "name": "src/flutter",
              "url": "https://github.com/flutter/engine.git",
              "custom_deps": {},
              "deps_file": "DEPS",
              "safesync_url": "",
            },
          ]
          EOF
          gclient sync
      
      - name: 配置Android SDK
        run: |
          mkdir -p android-sdk
          cd android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip commandlinetools-linux-8092744_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          rm -rf cmdline-tools/latest/cmdline-tools || true
          echo "ANDROID_HOME=$PWD" >> $GITHUB_ENV
          echo "PATH=$PWD/cmdline-tools/latest/bin:$PWD/platform-tools:$PATH" >> $GITHUB_ENV
          
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;25.1.8937393"
      
      - name: 配置构建参数
        run: |
          cd flutter-engine/src
          ./flutter/tools/gn --runtime-mode=release --android --android-cpu=arm64
      
      - name: 编译Flutter Engine
        run: |
          cd flutter-engine/src
          ninja -C out/android_release_arm64
      
      - name: 导出编译产物
        uses: actions/upload-artifact@v3
        with:
          name: flutter-engine-android-arm64
          path: |
            flutter-engine/src/out/android_release_arm64/clang_x64
            flutter-engine/src/out/android_release_arm64/gen
            flutter-engine/src/out/android_release_arm64/*.so
            flutter-engine/src/out/android_release_arm64/*.jar
