name: 构建Flutter Engine (Linux ARM64)

on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      flutter_engine_version:
        description: 'Flutter Engine版本(分支或标签)'
        required: true
        default: 'main'
        type: string
  # 定时构建，每周一早上6点
  schedule:
    - cron: '0 6 * * 1'
  # 当推送到主分支时触发
  push:
    branches: [ main ]

jobs:
  build:
    name: 构建Linux ARM64版本引擎
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 安装依赖项
        run: |
          sudo apt-get update
          # 安装编译依赖
          sudo apt-get install -y curl git unzip python3 python3-pip pkg-config cmake ninja-build clang libgtk-3-dev liblzma-dev libstdc++-10-dev
          # 安装ARM64交叉编译工具
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: 设置depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 缓存Flutter Engine
        id: cache-engine-source
        uses: actions/cache@v4
        with:
          path: engine
          key: flutter-engine-${{ github.event.inputs.flutter_engine_version || 'main' }}-${{ hashFiles('engine/.git/HEAD') }}
          restore-keys: |
            flutter-engine-${{ github.event.inputs.flutter_engine_version || 'main' }}-

      - name: 下载Flutter Engine源码
        if: steps.cache-engine-source.outputs.cache-hit != 'true'
        run: |
          mkdir -p engine
          cd engine
          # 获取Flutter Engine代码
          git clone https://github.com/flutter/engine.git src/flutter
          cd src/flutter
          git checkout ${{ github.event.inputs.flutter_engine_version || 'main' }}
          # 获取引擎依赖的代码
          cd ..
          flutter/tools/gclient sync -D

      - name: 配置构建环境
        run: |
          cd engine/src
          # 创建用于ARM64构建的gclient配置
          cat > .gclient <<EOF
          solutions = [
            {
              "managed": False,
              "name": "src/flutter",
              "url": "https://github.com/flutter/engine.git",
              "custom_deps": {},
              "deps_file": "DEPS",
              "safesync_url": "",
            },
          ]
          EOF

      - name: 生成构建文件
        run: |
          cd engine/src
          # 配置ARM64构建
          ./flutter/tools/gn --target-os=linux --target-cpu=arm64 --runtime-mode=release --no-lto --no-goma

      - name: 编译Flutter Engine
        run: |
          cd engine/src
          ninja -C out/linux_release_arm64

      - name: 打包产物
        run: |
          cd engine/src
          mkdir -p flutter_engine_artifacts
          # 复制编译好的so文件和相关资源
          cp -r out/linux_release_arm64/so/lib/*.so flutter_engine_artifacts/
          cp -r out/linux_release_arm64/flutter_embedder.h flutter_engine_artifacts/
          # 压缩产物
          tar -czvf flutter_engine_linux_arm64.tar.gz flutter_engine_artifacts

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: flutter-engine-linux-arm64
          path: engine/src/flutter_engine_linux_arm64.tar.gz
          retention-days: 7

      - name: 创建发布（如果从标签触发）
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: engine/src/flutter_engine_linux_arm64.tar.gz
          name: Flutter Engine Linux ARM64 - ${{ github.ref_name }}
          body: |
            Flutter Engine Linux ARM64 构建版本
            
            版本: ${{ github.event.inputs.flutter_engine_version || github.ref_name || 'main' }}
            构建时间: ${{ github.event.repository.updated_at }}
