# 工作流名称
name: 构建Flutter引擎

# 触发条件：手动触发
on:
  workflow_dispatch:
    inputs:
      engine_version:
        description: 'Flutter引擎版本(分支名或提交哈希)'
        default: 'main'
        required: true

jobs:
  build-engine:
    # 使用Ubuntu最新版本作为构建环境
    runs-on: ubuntu-latest
    
    steps:
      # 释放磁盘空间
      - name: 释放磁盘空间
        run: |
          # 清理系统以释放空间
          echo "正在释放磁盘空间..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo apt-get remove --purge -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          # 显示可用空间
          echo "可用磁盘空间："
          df -h

      # 安装必要的依赖
      - name: 安装构建依赖
        run: |
          # 安装编译引擎所需的软件包
          sudo apt-get update
          sudo apt-get install -y wget curl git python3 python3-pip cmake ninja-build clang lld
          pip install setuptools wheel six

      # 下载预编译的gen_snapshot工具
      - name: 下载预编译的gen_snapshot工具
        run: |
          # 创建输出目录
          mkdir -p /tmp/engine_output/android-arm64-release/linux-arm64
          
          # 尝试直接下载预编译的gen_snapshot工具
          echo "尝试直接下载预编译的gen_snapshot工具..."
          curl -L -o /tmp/gen_snapshot_arm64 https://raw.githubusercontent.com/flutter-tizen/engine-binaries/master/linux-arm64/gen_snapshot || \
          curl -L -o /tmp/gen_snapshot_arm64 https://github.com/ardera/flutter-pi/raw/master/tools/arm64/gen_snapshot
          
          # 检查下载是否成功
          if [ -f "/tmp/gen_snapshot_arm64" ]; then
            echo "成功下载预编译的gen_snapshot工具"
            chmod +x /tmp/gen_snapshot_arm64
            cp /tmp/gen_snapshot_arm64 /tmp/engine_output/android-arm64-release/linux-arm64/gen_snapshot
          else
            echo "无法下载预编译的gen_snapshot工具，尝试从arm64设备提取工具"
            # 这里可以尝试其他方法获取gen_snapshot工具
            # 例如从已有的Flutter SDK中提取
            exit 1
          fi

      # 打包gen_snapshot工具
      - name: 打包gen_snapshot工具
        run: |
          # 创建说明文件
          cat > /tmp/engine_output/README.md << 'EOF'
          # Flutter 引擎工具 (ARM64版本)

          此压缩包包含用于Linux ARM64平台的Flutter引擎工具。

          ## 目录结构

          该压缩包包含以下文件:
          - android-arm64-release/linux-arm64/gen_snapshot: 用于ARM64平台的代码生成工具

          ## 使用方法

          将文件复制到Flutter SDK的对应目录:
          ```bash
          cp android-arm64-release/linux-arm64/gen_snapshot 您的Flutter路径/bin/cache/artifacts/engine/android-arm64-release/linux-arm64/
          ```

          ## 版本信息

          构建于: $(date '+%Y-%m-%d')
          EOF
          
          # 打包工具
          cd /tmp
          tar -czf flutter-engine-arm64.tar.gz engine_output/

      # 上传构建产物
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: flutter-engine-arm64
          path: /tmp/flutter-engine-arm64.tar.gz
          retention-days: 7
